name: CI

on:
  push:
    branches: [main, int]
  pull_request:
    branches: [main, int]

jobs:
  call-reusable-ci:
    permissions:
      contents: read
    uses: ./.github/workflows/reusable-ci.yml
